language: c
sudo: required
services:
    - docker
env:
    - OS_TYPE=centos:7
    - OS_TYPE=opensuse
    - OS_TYPE=debian:8
before_install:
    - .github/runchecks
    - docker pull ${OS_TYPE}
    - docker run -it -d -h testdev.pbspro.com --name testdev -v `pwd`:`pwd` --privileged -w `pwd` ${OS_TYPE} /bin/sh
    - docker ps -a
    - export DOCKER_EXEC_TTY="docker exec -it testdev"
    - export DOCKER_EXEC="docker exec -i testdev"
    - export DOCKER_TESTDEV_IP="$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' testdev)"
    - ${DOCKER_EXEC} /bin/sh -c "echo '${DOCKER_TESTDEV_IP}     testdev' >> /etc/hosts"
    - ${DOCKER_EXEC} cat /etc/hosts
install:
    - ./.travis/${OS_TYPE//:/_}.sh
    - ${DOCKER_EXEC} /bin/sh -c "cd test/fw; pip install -r requirements.txt ."
    - ${DOCKER_EXEC_TTY} pbs_config --make-ug
    - ${DOCKER_EXEC_TTY} /bin/sh -c "cd test/tests; pbs_benchpress -l INFOCLI2 -o ../../ptl.txt --tags=smoke"
script: true

